version: "2"

services:

  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - NODE_ENV=$NODE_ENV

  postgres:
    image: postgres:9.6.2-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:
      POSTGRES_USER: 
      POSTGRES_PASSWORD:

  postgres_test:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
